CREATE SCHEMA IF NOT EXISTS tomorrowio;

CREATE TABLE IF NOT EXISTS tomorrowio.forecasts (
    createdat TIMESTAMP,
    predictiontime TIMESTAMP,
    cloudBase FLOAT,
    cloudCeiling FLOAT,
    cloudCover FLOAT,
    dewPoint FLOAT,
    evapotranspiration FLOAT,
    freezingRainIntensity FLOAT,
    humidity FLOAT,
    iceAccumulation FLOAT,
    iceAccumulationLwe FLOAT,
    precipitationProbability FLOAT,
    pressureSurfaceLevel FLOAT,
    rainAccumulation FLOAT,
    rainAccumulationLwe FLOAT,
    rainIntensity FLOAT,
    sleetAccumulation FLOAT,
    sleetAccumulationLwe FLOAT,
    sleetIntensity FLOAT,
    snowAccumulation FLOAT,
    snowAccumulationLwe FLOAT,
    snowDepth FLOAT,
    snowIntensity FLOAT,
    temperature FLOAT,
    temperatureApparent FLOAT,
    uvHealthConcern FLOAT,
    uvIndex FLOAT,
    visibility FLOAT,
    weatherCode FLOAT,
    windDirection FLOAT,
    windGust FLOAT,
    windSpeed FLOAT,
    lat FLOAT,
    lon FLOAT,
    PRIMARY KEY (createdat, predictiontime, lat, lon)
);

CREATE TABLE IF NOT EXISTS tomorrowio.recent_weather_history (
    historicaltime TIMESTAMP,
    cloudBase FLOAT,
    cloudCeiling FLOAT,
    cloudCover FLOAT,
    dewPoint FLOAT,
    evapotranspiration FLOAT,
    freezingRainIntensity FLOAT,
    humidity FLOAT,
    iceAccumulation FLOAT,
    iceAccumulationLwe FLOAT,
    precipitationProbability FLOAT,
    pressureSurfaceLevel FLOAT,
    rainAccumulation FLOAT,
    rainAccumulationLwe FLOAT,
    rainIntensity FLOAT,
    sleetAccumulation FLOAT,
    sleetAccumulationLwe FLOAT,
    sleetIntensity FLOAT,
    snowAccumulation FLOAT,
    snowAccumulationLwe FLOAT,
    snowDepth FLOAT,
    snowIntensity FLOAT,
    temperature FLOAT,
    temperatureApparent FLOAT,
    uvHealthConcern FLOAT,
    uvIndex FLOAT,
    visibility FLOAT,
    weatherCode FLOAT,
    windDirection FLOAT,
    windGust FLOAT,
    windSpeed FLOAT,
    lat FLOAT,
    lon FLOAT,
    PRIMARY KEY (historicaltime, lat, lon)
);
